name: Deploy to Production

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: SSH into EC2 and deploy
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /path/to/application
            git pull origin main
            bundle install --path vendor/bundle --without test development
            bundle exec rails assets:precompile RAILS_ENV=production
            bundle exec rails db:migrate RAILS_ENV=production
            sudo kill $(cat tmp/pids/puma.pid)
            rails s -e production &
          EOF

      - name: Check deployment
        run: |
          sleep 30 # wait for server to start
          curl http://${{ secrets.EC2_PUBLIC_IP }} # replace with actual URL